#define ROOT_NO_AUTOLOAD_DICT
#include <TApplication.h>
#include "CompareHistosGUI.h"

// forward declare the dictionary init function generated by rootcling/rootcint
//extern "C" void TriggerDictionaryInitialization_libCompareHistosGUI_Impl();
extern "C" void TriggerDictionaryInitialization_G__CompareHistosGUI_Impl();

int main(int argc, char** argv){
    TApplication app("CompareHistosGUI",&argc,argv);

    // Ensure the generated dictionary is registered with Cling

    //TriggerDictionaryInitialization_libCompareHistosGUI_Impl();
    TriggerDictionaryInitialization_G__CompareHistosGUI_Impl();
    CompareHistosGUI gui(gClient->GetRoot());
    app.Run();
    return 0;
}
